export const aioTableLabels = [
  {
    text: 'In-active',
    textClass: 'text-green',
    bgClass: 'bg-green-light',
    previewClass: 'bg-green'
  },
  {
    text: 'Active',
    textClass: 'text-cyan',
    bgClass: 'bg-cyan-light',
    previewClass: 'bg-cyan'
  },
  {
    text: 'In Progress',
    textClass: 'text-teal',
    bgClass: 'bg-teal-light',
    previewClass: 'bg-teal'
  },
  {
    text: 'Completed',
    textClass: 'text-purple',
    bgClass: 'bg-purple-light',
    previewClass: 'bg-purple'
  },
];

export const aioTableData = [
  {
    id: 0,
    imageSrc: 'assets/img/avatars/1.jpg',
    sku: 90803,
    description: 'Lorum Ipsum', 
    category: 'Custom Floor',
    firstName: 'Dejesus',
    lastName: 'Chang',
    street: '899 Raleigh Place',
    zipcode: 8057,
    city: 'Munjor',
    phoneNumber: '+32 (818) 580-3557',
    mail: 'dejesus.chang@yourcompany.biz',
    status: [aioTableLabels[0]],
    labels: [aioTableLabels[0]]
  },
  {
    id: 1,
    imageSrc: 'assets/img/avatars/1.jpg',
    sku: 90803,
    description: 'Lorum Ipsum', 
    category: 'Custom Floor',
    firstName: 'Dejesus',
    lastName: 'Chang',
    street: '899 Raleigh Place',
    zipcode: 8057,
    city: 'Munjor',
    phoneNumber: '+32 (818) 580-3557',
    mail: 'dejesus.chang@yourcompany.biz',
    status: [aioTableLabels[1]],
    labels: [aioTableLabels[1]]
  },
  {
    id: 2,
    imageSrc: 'assets/img/avatars/1.jpg',
    sku: 90803,
    description: 'Lorum Ipsum', 
    category: 'Custom Floor',
    firstName: 'Dejesus',
    lastName: 'Chang',
    street: '899 Raleigh Place',
    zipcode: 8057,
    city: 'Munjor',
    phoneNumber: '+32 (818) 580-3557',
    mail: 'dejesus.chang@yourcompany.biz',
    status: [aioTableLabels[0]],
    labels: [aioTableLabels[1]]
  },
  {
    id: 3,
    imageSrc: 'assets/img/avatars/1.jpg',
    sku: 90803,
    description: 'Lorum Ipsum', 
    category: 'Custom Floor',
    firstName: 'Dejesus',
    lastName: 'Chang',
    street: '899 Raleigh Place',
    zipcode: 8057,
    city: 'Munjor',
    phoneNumber: '+32 (818) 580-3557',
    mail: 'dejesus.chang@yourcompany.biz',
    status: [aioTableLabels[0]],
    labels: [aioTableLabels[1]]
  },
  {
    id: 4,
    imageSrc: 'assets/img/avatars/1.jpg',
    sku: 90803,
    description: 'Lorum Ipsum', 
    category: 'Custom Floor',
    firstName: 'Dejesus',
    lastName: 'Chang',
    street: '899 Raleigh Place',
    zipcode: 8057,
    city: 'Munjor',
    phoneNumber: '+32 (818) 580-3557',
    mail: 'dejesus.chang@yourcompany.biz',
    status: [aioTableLabels[0]],
    labels: [aioTableLabels[1]]
  },
  {
    id: 5,
    imageSrc: 'assets/img/avatars/1.jpg',
    sku: 90803,
    description: 'Lorum Ipsum', 
    category: 'Custom Floor',
    firstName: 'Dejesus',
    lastName: 'Chang',
    street: '899 Raleigh Place',
    zipcode: 8057,
    city: 'Munjor',
    phoneNumber: '+32 (818) 580-3557',
    mail: 'dejesus.chang@yourcompany.biz',
    status: [aioTableLabels[0]],
    labels: [aioTableLabels[1]]
  },
  {
    id: 6,
    imageSrc: 'assets/img/avatars/1.jpg',
    sku: 90803,
    description: 'Lorum Ipsum', 
    category: 'Custom Floor',
    firstName: 'Dejesus',
    lastName: 'Chang',
    street: '899 Raleigh Place',
    zipcode: 8057,
    city: 'Munjor',
    phoneNumber: '+32 (818) 580-3557',
    mail: 'dejesus.chang@yourcompany.biz',
    status: [aioTableLabels[0]],
    labels: [aioTableLabels[1]]
  },
  {
    id: 7,
    imageSrc: 'assets/img/avatars/1.jpg',
    sku: 90803,
    description: 'Lorum Ipsum', 
    category: 'Custom Floor',
    firstName: 'Dejesus',
    lastName: 'Chang',
    street: '899 Raleigh Place',
    zipcode: 8057,
    city: 'Munjor',
    phoneNumber: '+32 (818) 580-3557',
    mail: 'dejesus.chang@yourcompany.biz',
    status: [aioTableLabels[0]],
    labels: [aioTableLabels[1]]
  },
  {
    id: 8,
    imageSrc: 'assets/img/avatars/1.jpg',
    sku: 90803,
    description: 'Lorum Ipsum', 
    category: 'Custom Floor',
    firstName: 'Dejesus',
    lastName: 'Chang',
    street: '899 Raleigh Place',
    zipcode: 8057,
    city: 'Munjor',
    phoneNumber: '+32 (818) 580-3557',
    mail: 'dejesus.chang@yourcompany.biz',
    status: [aioTableLabels[0]],
    labels: [aioTableLabels[1]]
  },
  {
    id: 9,
    imageSrc: 'assets/img/avatars/1.jpg',
    sku: 90803,
    description: 'Lorum Ipsum', 
    category: 'Custom Floor',
    firstName: 'Dejesus',
    lastName: 'Chang',
    street: '899 Raleigh Place',
    zipcode: 8057,
    city: 'Munjor',
    phoneNumber: '+32 (818) 580-3557',
    mail: 'dejesus.chang@yourcompany.biz',
    status: [aioTableLabels[0]],
    labels: [aioTableLabels[1]]
  },
  {
    id: 10,
    imageSrc: 'assets/img/avatars/1.jpg',
    sku: 90803,
    description: 'Lorum Ipsum', 
    category: 'Custom Floor',
    firstName: 'Dejesus',
    lastName: 'Chang',
    street: '899 Raleigh Place',
    zipcode: 8057,
    city: 'Munjor',
    phoneNumber: '+32 (818) 580-3557',
    mail: 'dejesus.chang@yourcompany.biz',
    status: [aioTableLabels[0]],
    labels: [aioTableLabels[1]]
  },
  {
    id: 11,
    imageSrc: 'assets/img/avatars/1.jpg',
    sku: 90803,
    description: 'Lorum Ipsum', 
    category: 'Custom Floor',
    firstName: 'Dejesus',
    lastName: 'Chang',
    street: '899 Raleigh Place',
    zipcode: 8057,
    city: 'Munjor',
    phoneNumber: '+32 (818) 580-3557',
    mail: 'dejesus.chang@yourcompany.biz',
    status: [aioTableLabels[0]],
    labels: [aioTableLabels[1]]
  },
  {
    id: 12,
    imageSrc: 'assets/img/avatars/1.jpg',
    sku: 90803,
    description: 'Lorum Ipsum', 
    category: 'Custom Floor',
    firstName: 'Dejesus',
    lastName: 'Chang',
    street: '899 Raleigh Place',
    zipcode: 8057,
    city: 'Munjor',
    phoneNumber: '+32 (818) 580-3557',
    mail: 'dejesus.chang@yourcompany.biz',
    status: [aioTableLabels[0]],
    labels: [aioTableLabels[1]]
  },
  {
    id: 13,
    imageSrc: 'assets/img/avatars/1.jpg',
    sku: 90803,
    description: 'Lorum Ipsum', 
    category: 'Custom Floor',
    firstName: 'Dejesus',
    lastName: 'Chang',
    street: '899 Raleigh Place',
    zipcode: 8057,
    city: 'Munjor',
    phoneNumber: '+32 (818) 580-3557',
    mail: 'dejesus.chang@yourcompany.biz',
    status: [aioTableLabels[0]],
    labels: [aioTableLabels[1]]
  },
  {
    id: 14,
    imageSrc: 'assets/img/avatars/1.jpg',
    sku: 90803,
    description: 'Lorum Ipsum', 
    category: 'Custom Floor',
    firstName: 'Dejesus',
    lastName: 'Chang',
    street: '899 Raleigh Place',
    zipcode: 8057,
    city: 'Munjor',
    phoneNumber: '+32 (818) 580-3557',
    mail: 'dejesus.chang@yourcompany.biz',
    status: [aioTableLabels[0]],
    labels: [aioTableLabels[1]]
  },
  {
    id: 15,
    imageSrc: 'assets/img/avatars/1.jpg',
    sku: 90803,
    description: 'Lorum Ipsum', 
    category: 'Custom Floor',
    firstName: 'Dejesus',
    lastName: 'Chang',
    street: '899 Raleigh Place',
    zipcode: 8057,
    city: 'Munjor',
    phoneNumber: '+32 (818) 580-3557',
    mail: 'dejesus.chang@yourcompany.biz',
    status: [aioTableLabels[0]],
    labels: [aioTableLabels[1]]
  },
  {
    id: 16,
    imageSrc: 'assets/img/avatars/1.jpg',
    sku: 90803,
    description: 'Lorum Ipsum', 
    category: 'Custom Floor',
    firstName: 'Dejesus',
    lastName: 'Chang',
    street: '899 Raleigh Place',
    zipcode: 8057,
    city: 'Munjor',
    phoneNumber: '+32 (818) 580-3557',
    mail: 'dejesus.chang@yourcompany.biz',
    status: [aioTableLabels[0]],
    labels: [aioTableLabels[1]]
  },
  {
    id: 17,
    imageSrc: 'assets/img/avatars/1.jpg',
    sku: 90803,
    description: 'Lorum Ipsum', 
    category: 'Custom Floor',
    firstName: 'Dejesus',
    lastName: 'Chang',
    street: '899 Raleigh Place',
    zipcode: 8057,
    city: 'Munjor',
    phoneNumber: '+32 (818) 580-3557',
    mail: 'dejesus.chang@yourcompany.biz',
    status: [aioTableLabels[0]],
    labels: [aioTableLabels[1]]
  },
  {
    id: 18,
    imageSrc: 'assets/img/avatars/1.jpg',
    sku: 90803,
    description: 'Lorum Ipsum', 
    category: 'Custom Floor',
    firstName: 'Dejesus',
    lastName: 'Chang',
    street: '899 Raleigh Place',
    zipcode: 8057,
    city: 'Munjor',
    phoneNumber: '+32 (818) 580-3557',
    mail: 'dejesus.chang@yourcompany.biz',
    status: [aioTableLabels[0]],
    labels: [aioTableLabels[1]]
  },
  {
    id: 19,
    imageSrc: 'assets/img/avatars/1.jpg',
    sku: 90803,
    description: 'Lorum Ipsum', 
    category: 'Custom Floor',
    firstName: 'Dejesus',
    lastName: 'Chang',
    street: '899 Raleigh Place',
    zipcode: 8057,
    city: 'Munjor',
    phoneNumber: '+32 (818) 580-3557',
    mail: 'dejesus.chang@yourcompany.biz',
    status: [aioTableLabels[0]],
    labels: [aioTableLabels[1]]
  },
  {
    id: 20,
    imageSrc: 'assets/img/avatars/1.jpg',
    sku: 90803,
    description: 'Lorum Ipsum', 
    category: 'Custom Floor',
    firstName: 'Dejesus',
    lastName: 'Chang',
    street: '899 Raleigh Place',
    zipcode: 8057,
    city: 'Munjor',
    phoneNumber: '+32 (818) 580-3557',
    mail: 'dejesus.chang@yourcompany.biz',
    status: [aioTableLabels[0]],
    labels: [aioTableLabels[1]]
  },
  {
    id: 21,
    imageSrc: 'assets/img/avatars/1.jpg',
    sku: 90803,
    description: 'Lorum Ipsum', 
    category: 'Custom Floor',
    firstName: 'Dejesus',
    lastName: 'Chang',
    street: '899 Raleigh Place',
    zipcode: 8057,
    city: 'Munjor',
    phoneNumber: '+32 (818) 580-3557',
    mail: 'dejesus.chang@yourcompany.biz',
    status: [aioTableLabels[0]],
    labels: [aioTableLabels[1]]
  },
  {
    id: 22,
    imageSrc: 'assets/img/avatars/1.jpg',
    sku: 90803,
    description: 'Lorum Ipsum', 
    category: 'Custom Floor',
    firstName: 'Dejesus',
    lastName: 'Chang',
    street: '899 Raleigh Place',
    zipcode: 8057,
    city: 'Munjor',
    phoneNumber: '+32 (818) 580-3557',
    mail: 'dejesus.chang@yourcompany.biz',
    status: [aioTableLabels[0]],
    labels: [aioTableLabels[1]]
  },
  {
    id: 23,
    imageSrc: 'assets/img/avatars/1.jpg',
    sku: 90803,
    description: 'Lorum Ipsum', 
    category: 'Custom Floor',
    firstName: 'Dejesus',
    lastName: 'Chang',
    street: '899 Raleigh Place',
    zipcode: 8057,
    city: 'Munjor',
    phoneNumber: '+32 (818) 580-3557',
    mail: 'dejesus.chang@yourcompany.biz',
    status: [aioTableLabels[0]],
    labels: [aioTableLabels[1]]
  },
  {
    id: 24,
    imageSrc: 'assets/img/avatars/1.jpg',
    sku: 90803,
    description: 'Lorum Ipsum', 
    category: 'Custom Floor',
    firstName: 'Dejesus',
    lastName: 'Chang',
    street: '899 Raleigh Place',
    zipcode: 8057,
    city: 'Munjor',
    phoneNumber: '+32 (818) 580-3557',
    mail: 'dejesus.chang@yourcompany.biz',
    status: [aioTableLabels[0]],
    labels: [aioTableLabels[1]]
  },
  {
    id: 25,
    imageSrc: 'assets/img/avatars/1.jpg',
    sku: 90803,
    description: 'Lorum Ipsum', 
    category: 'Custom Floor',
    firstName: 'Dejesus',
    lastName: 'Chang',
    street: '899 Raleigh Place',
    zipcode: 8057,
    city: 'Munjor',
    phoneNumber: '+32 (818) 580-3557',
    mail: 'dejesus.chang@yourcompany.biz',
    status: [aioTableLabels[0]],
    labels: [aioTableLabels[1]]
  },
  {
    id: 26,
    iimageSrc: 'assets/img/avatars/1.jpg',
    sku: 90803,
    description: 'Lorum Ipsum', 
    category: 'Custom Floor',
    firstName: 'Dejesus',
    lastName: 'Chang',
    street: '899 Raleigh Place',
    zipcode: 8057,
    city: 'Munjor',
    phoneNumber: '+32 (818) 580-3557',
    mail: 'dejesus.chang@yourcompany.biz',
    status: [aioTableLabels[0]],
    labels: [aioTableLabels[1]]
  },
  {
    id: 27,
    imageSrc: 'assets/img/avatars/1.jpg',
    sku: 90803,
    description: 'Lorum Ipsum', 
    category: 'Custom Floor',
    firstName: 'Dejesus',
    lastName: 'Chang',
    street: '899 Raleigh Place',
    zipcode: 8057,
    city: 'Munjor',
    phoneNumber: '+32 (818) 580-3557',
    mail: 'dejesus.chang@yourcompany.biz',
    status: [aioTableLabels[0]],
    labels: [aioTableLabels[1]]
  },
  {
    id: 28,
    imageSrc: 'assets/img/avatars/1.jpg',
    sku: 90803,
    description: 'Lorum Ipsum', 
    category: 'Custom Floor',
    firstName: 'Dejesus',
    lastName: 'Chang',
    street: '899 Raleigh Place',
    zipcode: 8057,
    city: 'Munjor',
    phoneNumber: '+32 (818) 580-3557',
    mail: 'dejesus.chang@yourcompany.biz',
    status: [aioTableLabels[0]],
    labels: [aioTableLabels[1]]
  },
  {
    id: 29,
    imageSrc: 'assets/img/avatars/1.jpg',
    sku: 90803,
    description: 'Lorum Ipsum', 
    category: 'Custom Floor',
    firstName: 'Dejesus',
    lastName: 'Chang',
    street: '899 Raleigh Place',
    zipcode: 8057,
    city: 'Munjor',
    phoneNumber: '+32 (818) 580-3557',
    mail: 'dejesus.chang@yourcompany.biz',
    status: [aioTableLabels[0]],
    labels: [aioTableLabels[1]]
  }
];
